### ISSUE TITLE
Kanban board setup.

### ISSUE THREAD

**Issue by Leeoasis** [Leeoasis/ruby-recipe-app#13]
#### Link to the kanban project
- [ ] https://github.com/Leeoasis/ruby-recipe-app/projects/1 

- There are two people in this project.

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi team, 

To highlight 👍🏽 
✔️ Cards are added to the kanban board
✔️ All columns are present
✔️ Tasks are equally shared

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
